!Config

    LOGGING_LEVEL: 'INFO'

    APP_NAME: 'flairbot'
    VERSION: '1.0.0a'

    # donphan Configuration
    DONPHAN: !Config
        DSN: !ENV 'POSTGRECONNSTR'
        DELETE_TABLES_ON_STARTUP: no
        DELETE_VIEWS_ON_STARTUP: yes
        APPLICATION_NAME: 'r/Pokemon FlairBot'

    # Reddit Configuration
    REDDIT: !Config
        APP: !Config
            CLIENT_ID: !ENV 'REDDIT_APP_ID'
            CLIENT_SECRET: !ENV 'REDDIT_APP_SECRET'
        SCRIPT: !Config
            CLIENT_ID: !ENV 'REDDIT_SCRIPT_ID'
            CLIENT_SECRET: !ENV 'REDDIT_SCRIPT_SECRET'
        USERNAME: !ENV 'REDDIT_USERNAME'
        PASSWORD: !ENV 'REDDIT_PASSWORD'
        REDIRECT_URI: 'https://rpkmn.center/flair/login'

    # Web Server Configuration
    WEB: !Config
        HOST: 'localhost'
        PORT: 8081
        TEMPLATE_DIR: 'flair/templates'

    SUBREDDITS: [
        'Pokemon', 'Stunfisk', 'TruePokemon'
    ]